---
Name: betterbuttons
---
DataObject:
  extensions:
    - BetterButtonDataObject
GridFieldDetailForm_ItemRequest:
  extensions:
    - GridFieldBetterButtonsItemRequest
BetterButtonsUtils:
  edit:
    BetterButtonPrevNextAction: true
    BetterButtonNew: true
  versioned_edit:
    BetterButtonPrevNextAction: true
    BetterButtonNew: true

BetterButtonsActions:
  create:
    BetterButtonSave: true
    BetterButtonSaveAndClose: true

  edit:
    BetterButtonSave: true
    BetterButtonSaveAndClose: true
    BetterButtonDelete: true
    BetterButtonFrontendLinksAction: true

  versioned_create:
    BetterButtonSaveDraft: true
    BetterButtonPublish: true
  versioned_edit:
    BetterButtonSaveDraft: true
    BetterButtonPublish: true
    Group_Versioning: true
    BetterButtonDelete: true
    BetterButtonFrontendLinksAction: true

BetterButtonsGroups:
  SaveAnd:
    label: Save and...
    buttons:
      BetterButtonSaveAndAdd: true
      BetterButtonSaveAndClose: true
      BetterButtonSaveAndNext: true
      BetterButtonSaveAndPrev: true
  Versioning:
    label: Versioning...
    buttons:
      BetterButtonRollback: true
      BetterButton_Unpublish: true

