---
Name: betterbuttons
---
GridFieldDetailForm_ItemRequest:
  extensions:
    - GridFieldBetterButtonsItemRequest
BetterButtonsViews:
  create:
    Button_Save: true    
    Button_SaveAndClose: true
    Button_Cancel: true
  edit:
    Button_FrontendLinks: true 
    Button_Save: true
    Button_SaveAndClose: true
    Button_New: true
    Button_Cancel: true
    Button_Delete: true

  versioned_create:
    Button_SaveDraft: true
    Button_Publish: true    
    Button_Cancel: true
  versioned_edit:
    Button_FrontendLinks: true
    Button_SaveDraft: true
    Button_Publish: true    
    Button_New: true
    Group_Versioning: true    
    Button_Cancel: true
    Button_Delete: true

BetterButtonsGroups:
  SaveAnd:
    label: Save and...
    buttons:
      Button_SaveAndAdd: true
      Button_SaveAndClose: true
      Button_SaveAndNext: true
      Button_SaveAndPrev: true
  Versioning:
    label: Versioning...
    buttons:
      Button_Rollback: true
      Button_Unpublish: true

